server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:9091
#          predicates:
#            - Path= /customers/**
#
#        - id: r2
#          uri: http://localhost:9092
#          predicates:
#            - Path= /inventories/**
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30